In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Upernavik,GL,72.7868,-56.1549,16.45,83,76,6.62,broken clouds
1,1,Saskylakh,RU,71.9167,114.0833,13.95,93,100,10.18,overcast clouds
2,2,Saint Paul Harbor,US,57.7900,-152.4072,35.11,93,100,9.22,moderate rain
3,3,Mataura,NZ,-46.1927,168.8643,62.11,62,34,5.28,scattered clouds
4,4,Hobart,AU,-42.8794,147.3294,59.25,52,75,14.97,broken clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
22,22,Mogadishu,SO,2.0371,45.3438,79.79,76,54,10.76,broken clouds
23,23,Toamasina,MG,-18.1667,49.3833,77.23,62,74,1.23,broken clouds
30,30,Kavieng,PG,-2.5744,150.7967,85.08,65,73,1.79,broken clouds
31,31,Vaini,TO,-21.2000,-175.2000,77.16,94,100,6.91,light rain
32,32,Faanui,PF,-16.4833,-151.7500,77.11,81,54,13.76,light rain
34,34,Mareeba,AU,-17.0000,145.4333,87.44,71,47,7.72,scattered clouds
35,35,Atuona,PF,-9.8000,-139.0333,77.09,74,3,10.98,clear sky
37,37,Kapaa,US,22.0752,-159.3190,78.78,82,0,16.11,clear sky
38,38,Luganville,VU,-15.5333,167.1667,83.19,68,15,7.36,few clouds
40,40,Auki,SB,-8.7676,160.7034,82.42,78,57,2.98,broken clouds

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                177
City                   177
Country                177
Lat                    177
Lng                    177
Max Temp               177
Humidity               177
Cloudiness             177
Wind Speed             177
Current Description    177
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()

In [7]:
# 4a. Determine if there are any empty rows.
clean_df.count()

City_ID                177
City                   177
Country                177
Lat                    177
Lng                    177
Max Temp               177
Humidity               177
Cloudiness             177
Wind Speed             177
Current Description    177
dtype: int64

In [8]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
22,Mogadishu,SO,79.79,broken clouds,2.0371,45.3438,
23,Toamasina,MG,77.23,broken clouds,-18.1667,49.3833,
30,Kavieng,PG,85.08,broken clouds,-2.5744,150.7967,
31,Vaini,TO,77.16,light rain,-21.2000,-175.2000,
32,Faanui,PF,77.11,light rain,-16.4833,-151.7500,
34,Mareeba,AU,87.44,scattered clouds,-17.0000,145.4333,
35,Atuona,PF,77.09,clear sky,-9.8000,-139.0333,
37,Kapaa,US,78.78,clear sky,22.0752,-159.3190,
38,Luganville,VU,83.19,few clouds,-15.5333,167.1667,
40,Auki,SB,82.42,broken clouds,-8.7676,160.7034,

In [9]:
# 6a. Set parameters to search for hotels with 5000 meters for philadelphia
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key,
    "location": "39.952583,-75.16522"
}
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
hotels_phi = requests.get(base_url, params=params)
hotels_phi.json()

{'html_attributions': [],
 'next_page_token': 'AcYSjRj0ZI33CzVzMiUL7CPuYOzSJHqp72AjnpDEBTu0-BnHjG1Zf9CDqqkGsi5JvkxlCqzdOmWiVDjlpaIYtoN1MVe7Fatx1USYHvl25Fsvgee65x5uiAjnLCTGQBY170wMpuwjmX8bi2MAvbBlbKXEh4LGncfs8mpBEeWAuNzG4voo75m1lGLoCVvMjuL4R_3bTZgIBKhoAliweTTwE-c7Wcb340Va3yfE9_MppaO9bkmnXGkDnpwKUX2tUnUdp6oB37ZLUgQ4CnzyJkQ2Gwls1wyUE9iaecWW8Wm0xtLnNm5fsPVdbguO1jpK3m0lE39668tkdmU6IFvrFyRTiFOKvYu1lp419lmfiZgqEfI1ks-WRUflmG7MI0UAfuO-WSerK3qSt1QP98P3WtoXrstnb2Dr-QARkwacwKI2lSqRcv3GK6CitsP17mtf',
 'results': [{'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.95144560000001, 'lng': -75.1641494},
    'viewport': {'northeast': {'lat': 39.9527542302915,
      'lng': -75.16273601970849},
     'southwest': {'lat': 39.9500562697085, 'lng': -75.1654339802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'The Ritz-Carlton, Philadelphia',
   'photos': [{'height': 2048,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/110307673324163831209">The Ritz-Carlton, Philadelphia</a>'],
     'photo_reference': 'AcYSjRhkIplYOzhn84J5CvCcy9UUMstwdy4k0BbEoUwOLvBmo4QXirIlK6f9cQg-kaOsotlKMev2ZCQA5pFhj0e2tqt160hzsmQYVQg2Iv4oYfN8fciuk1VwJLy-eoyAr9mf3PKVW474IC6LC52OETy1DpIy1JY2A0TBM94UhiTY5XDkiNUA',
     'width': 1366}],
   'place_id': 'ChIJv51-sC_GxokR6fV5EFtVIyc',
   'plus_code': {'compound_code': 'XR2P+H8 Philadelphia, PA, USA',
    'global_code': '87F6XR2P+H8'},
   'price_level': 3,
   'rating': 4.4,
   'reference': 'ChIJv51-sC_GxokR6fV5EFtVIyc',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 1951,
   'vicinity': '10 Avenue Of The Arts, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.9526485, 'lng': -75.1621109},
    'viewport': {'northeast': {'lat': 39.9539964302915,
      'lng': -75.1609723697085},
     'southwest': {'lat': 39.9512984697085, 'lng': -75.16367033029151}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Residence Inn by Marriott Philadelphia Center City',
   'photos': [{'height': 4032,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114708714675201651378">Julie Nichols</a>'],
     'photo_reference': 'AcYSjRgpaJfra8C3U6Y3yh-qK9ROaHEBDgKnW-hIaXK97-nC3L6ccM_jyGKPu9GG5HDOEi6H1e80VCPsboLRNvAN_AKWxsdtC1ed3_oVt0u-S4bT8KP7k4bGOInBP2aEm2DeYwUvtoc_InSadjORMfWRCH5k_10idofmBL_p08Be-iJUPOu4',
     'width': 3024}],
   'place_id': 'ChIJdTu_7S7GxokR97kxJyXerfU',
   'plus_code': {'compound_code': 'XR3Q+35 Philadelphia, PA, USA',
    'global_code': '87F6XR3Q+35'},
   'rating': 4.2,
   'reference': 'ChIJdTu_7S7GxokR97kxJyXerfU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 1304,
   'vicinity': 'One East Penn Square, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.95486700000001,
     'lng': -75.16414139999999},
    'viewport': {'northeast': {'lat': 39.9560422802915,
      'lng': -75.1628017697085},
     'southwest': {'lat': 39.95334431970851, 'lng': -75.1654997302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Le Méridien Philadelphia',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2048,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/104314711510842309587">Le Méridien Philadelphia</a>'],
     'photo_reference': 'AcYSjRgxJJDxKl_myu4fCgQQx4C5u-NsmI1b2vVRK2nJrx5jKjbwY2ibuywMVd4D-LBsLDy3xZh2RpR55v7-YL3dwpNOw_NwPsx5aIR_PI6yi-gRUzD6zLHAFdv3dpXj3pWOVI5EsmsXFkOKEVCjsqqRrUDgYggq6Nv1rK8nz-Uzg_SkUHnr',
     'width': 1366}],
   'place_id': 'ChIJNyI72i3GxokRbboLZHgUf_8',
   'plus_code': {'compound_code': 'XR3P+W8 Philadelphia, PA, USA',
    'global_code': '87F6XR3P+W8'},
   'rating': 4.2,
   'reference': 'ChIJNyI72i3GxokRbboLZHgUf_8',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 1448,
   'vicinity': '1421 Arch Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.9521123, 'lng': -75.1684916},
    'viewport': {'northeast': {'lat': 39.9534683302915,
      'lng': -75.1672094697085},
     'southwest': {'lat': 39.9507703697085, 'lng': -75.16990743029152}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'The Westin Philadelphia',
   'photos': [{'height': 1920,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/104744888064695878148">Maurice “RizzRollex” Dugan</a>'],
     'photo_reference': 'AcYSjRjtazbYeNTaz_UcCeOm8bxvMFeztXLZjraJPSfSF4gjxSHpbKG4t98wLqIjURQqADHJwbieCq290J2TZ9Zk_DKbLjHOfNLa40p-kQRpNFccpwW_y-OQIQSYBIM6pjXQXOzT7Vs5hby-uQA9NPv44KLX1Wfv4Gyb5ZnHrZmE6Zbs8Jdy',
     'width': 1080}],
   'place_id': 'ChIJ6_1xXDDGxokRIQqqKZGjCNg',
   'plus_code': {'compound_code': 'XR2J+RJ Philadelphia, PA, USA',
    'global_code': '87F6XR2J+RJ'},
   'price_level': 3,
   'rating': 4.2,
   'reference': 'ChIJ6_1xXDDGxokRIQqqKZGjCNg',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 948,
   'vicinity': 'At, Liberty Place, 99 South 17th Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.95300650000001, 'lng': -75.1617435},
    'viewport': {'northeast': {'lat': 39.9543879302915,
      'lng': -75.16067606970849},
     'southwest': {'lat': 39.9516899697085, 'lng': -75.16337403029151}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'The Notary Hotel, Philadelphia, Autograph Collection',
   'photos': [{'height': 1366,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114199015026172908274">The Notary Hotel, Philadelphia, Autograph Collection</a>'],
     'photo_reference': 'AcYSjRjL91OeVpcb3Un3GTmAZZKLLC8DbtVRVHCuRMHLSvTiOS6_LaHngMER2TrxJStDlvxQG-bEBqzHtATN7bPGg02o1KtoJeK2UKdRrYh9ytnFD0JVgkw91CWZ1bn9SSQtqV3acN8333VudThwBRLVXYprmvuMDDRp0PYY_Igr61odjbVm',
     'width': 2048}],
   'place_id': 'ChIJkWOsky7GxokRRVwy9AGBEDU',
   'plus_code': {'compound_code': 'XR3Q+68 Philadelphia, PA, USA',
    'global_code': '87F6XR3Q+68'},
   'rating': 4.4,
   'reference': 'ChIJkWOsky7GxokRRVwy9AGBEDU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 2718,
   'vicinity': '21 North Juniper Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.9512234, 'lng': -75.1684003},
    'viewport': {'northeast': {'lat': 39.9526733802915,
      'lng': -75.1670255197085},
     'southwest': {'lat': 39.9499754197085, 'lng': -75.16972348029151}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Club Quarters Hotel Rittenhouse Square, Philadelphia',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1356,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/106194998780859366357">Club Quarters Hotel, Philadelphia, Rittenhouse Square</a>'],
     'photo_reference': 'AcYSjRhFh8iinm5n5fno7Ct1CwIQ_OxogdjncRjWG6tBFSCQSlv0Er8oF_5JBugaIY-pjLZL4lqYOPNxWnqZeXc9KBxMuOmVmR1gkG5KEywGTBXIsG-37zRjHLtKQtc7WqRr-F3b5KPy9pfJQfWGQ6UT1HJURO0FOo407Pemu0QhbiX-Sxe2',
     'width': 2048}],
   'place_id': 'ChIJUXdDXDDGxokR9rLmamBhX88',
   'plus_code': {'compound_code': 'XR2J+FJ Philadelphia, PA, USA',
    'global_code': '87F6XR2J+FJ'},
   'rating': 3.9,
   'reference': 'ChIJUXdDXDDGxokR9rLmamBhX88',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 2152,
   'vicinity': '1628 Chestnut Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.95078150000001, 'lng': -75.1686419},
    'viewport': {'northeast': {'lat': 39.9521687302915,
      'lng': -75.16742716970849},
     'southwest': {'lat': 39.9494707697085, 'lng': -75.17012513029151}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Kimpton Hotel Palomar Philadelphia',
   'photos': [{'height': 2138,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101918251476521929087">Kimpton Hotel Palomar Philadelphia</a>'],
     'photo_reference': 'AcYSjRjECyy4bHDDuJlNKLQkQ1U_RFXe2IHwoPrbIiB3xfvigWSeEOPUbGsUZCLMkDH0OD9eVy4aO4wJH_392j13zbkIJYJl2sxo-TElMFAdc3EFyQ-0g4QDtJW61zsWOV5R1mVQl3a5_NG2J33yGzjA59R6Hy7VYZiZ4gvISYAUQDnLFOcS',
     'width': 3938}],
   'place_id': 'ChIJD55aYTDGxokRuW1PyOVzdxQ',
   'plus_code': {'compound_code': 'XR2J+8G Philadelphia, PA, USA',
    'global_code': '87F6XR2J+8G'},
   'price_level': 3,
   'rating': 4.4,
   'reference': 'ChIJD55aYTDGxokRuW1PyOVzdxQ',
   'scope': 'GOOGLE',
   'types': ['lodging',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 1453,
   'vicinity': '117 South 17th Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.95084739999999, 'lng': -75.1691058},
    'viewport': {'northeast': {'lat': 39.95221328029149,
      'lng': -75.1676571697085},
     'southwest': {'lat': 39.94951531970849, 'lng': -75.17035513029151}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Sofitel Philadelphia at Rittenhouse Square',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3840,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114227411825662988006">Hotel Sofitel Philadelphia at Rittenhouse Square</a>'],
     'photo_reference': 'AcYSjRiBkZSiCJ2mWSiG2U57-iMR2RAxrdfylG6hSHfB-awm0wWLP-wYt2VpkBBQgyIlwhrGu941sz3mFDVdJNO9kjAB2Wvjv3Fo9CgDc4GP-k35jfv-sxwN7kwISZ-YxStub2VaGyQ0P2vEG07zgPZ7G0JBygesANOIt-Tt5qFWP-f7csZ9',
     'width': 5760}],
   'place_id': 'ChIJrQbSYzDGxokR2TCy3fjNWoQ',
   'plus_code': {'compound_code': 'XR2J+89 Philadelphia, PA, USA',
    'global_code': '87F6XR2J+89'},
   'price_level': 3,
   'rating': 4.4,
   'reference': 'ChIJrQbSYzDGxokR2TCy3fjNWoQ',
   'scope': 'GOOGLE',
   'types': ['lodging',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 2143,
   'vicinity': '120 South 17th Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.9526035, 'lng': -75.16062459999999},
    'viewport': {'northeast': {'lat': 39.9537726802915,
      'lng': -75.15929566970848},
     'southwest': {'lat': 39.9510747197085, 'lng': -75.1619936302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Philadelphia Marriott Downtown',
   'photos': [{'height': 810,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113519425381372019862">Philadelphia Marriott Downtown</a>'],
     'photo_reference': 'AcYSjRhNR3FmgivwH24U4-MosOLAY5df73L5g6I_j3KxsN4i9QPtHk8lkTQvydtnII-KcIc6wKZHnXjdKtjspd2WSzLPaOtmy_FLALEiB2BUKXZUnuNfZDd7xEa3S5Ksl9lAu-x0kcdV8iPxq-_bXJ-Ui65yOBs8JTIzXstJHDOFpoGfttM4',
     'width': 1440}],
   'place_id': 'ChIJOx8izC7GxokRPvOWsXcBRXs',
   'plus_code': {'compound_code': 'XR3Q+2Q Philadelphia, PA, USA',
    'global_code': '87F6XR3Q+2Q'},
   'price_level': 3,
   'rating': 4.2,
   'reference': 'ChIJOx8izC7GxokRPvOWsXcBRXs',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 6746,
   'vicinity': 'Guest Entrance At, 1201 Market Street, 1200 Filbert Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.9557325, 'lng': -75.1681478},
    'viewport': {'northeast': {'lat': 39.95713563029149,
      'lng': -75.16665086970849},
     'southwest': {'lat': 39.95443766970849, 'lng': -75.16934883029151}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'The Windsor Suites',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3840,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/109479920759808198512">The Windsor Suites</a>'],
     'photo_reference': 'AcYSjRg0g9IPD1D_4SAi_A4vb0a6UaO6ixsJX0hz3SVLbSLpYnpDS5nWkfVAyhRHScek3FG2QQPHCflRPr_VjIvvg8G1UaNU7z_VFswL4xmQ4e2iJ0_N6TS-HIW7XB_xSmlyP0ufZZyDQ9iDIxQ2mxIk1hh6se-mL3F5rnPJj_8N8hSEvloJ',
     'width': 5760}],
   'place_id': 'ChIJdVCkPzLGxokRZYFGa7RAGlc',
   'plus_code': {'compound_code': 'XR4J+7P Philadelphia, PA, USA',
    'global_code': '87F6XR4J+7P'},
   'rating': 4.1,
   'reference': 'ChIJdVCkPzLGxokRZYFGa7RAGlc',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 661,
   'vicinity': '1700 Benjamin Franklin Parkway, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.949357, 'lng': -75.1623767},
    'viewport': {'northeast': {'lat': 39.9506045302915,
      'lng': -75.16121216970849},
     'southwest': {'lat': 39.9479065697085, 'lng': -75.1639101302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Holiday Inn Express Philadelphia-Midtown, an IHG Hotel',
   'photos': [{'height': 1526,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114795943691915946461">Holiday Inn Express Philadelphia-Midtown, an IHG Hotel</a>'],
     'photo_reference': 'AcYSjRha2G5qe9asKwO2GO2Bas8RTG4h2g89G-VlVXzgcPRsgoLD9l8MDZ0PW4IPvne_kbZ5Ccf1bWBMtjZ7stCc5riSbNmX8QZjqo5otnijEEjiBcR4GHGjHC27YZbdcu6xEVFIEAN2u1JfkmWGLYUT9QFmjT-0PhELaH4cjgdhc4CoRb3h',
     'width': 2048}],
   'place_id': 'ChIJj7NcYi_GxokRN-XxX1zeGsQ',
   'plus_code': {'compound_code': 'WRXQ+P2 Philadelphia, PA, USA',
    'global_code': '87F6WRXQ+P2'},
   'rating': 4.2,
   'reference': 'ChIJj7NcYi_GxokRN-XxX1zeGsQ',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 1176,
   'vicinity': '1305 Walnut Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.9515991, 'lng': -75.1602673},
    'viewport': {'northeast': {'lat': 39.9531279302915,
      'lng': -75.15890191970848},
     'southwest': {'lat': 39.9504299697085, 'lng': -75.1615998802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Loews Philadelphia Hotel',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1192,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111105514513926266494">Loews Philadelphia Hotel</a>'],
     'photo_reference': 'AcYSjRgCM8bjq1VlPvwiRiss-ulXnXUkQ3w5I7eATnjCGC-7m086uThx1JWXsoDMzjZaf2RIx1iwiY8Q2uSrx0LNJ5MBx2SlIon1Sf2TXIvqXialwhp86-vUT4cTPPspNgDIbUicDZnc0E6-jfwAacRb_gw59TRq43PZcch6RlxgGTzrV8yd',
     'width': 2120}],
   'place_id': 'ChIJ6bNuLSnGxokR29Oj-g9Tojo',
   'plus_code': {'compound_code': 'XR2Q+JV Philadelphia, PA, USA',
    'global_code': '87F6XR2Q+JV'},
   'rating': 4.4,
   'reference': 'ChIJ6bNuLSnGxokR29Oj-g9Tojo',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 4511,
   'vicinity': '1200 Market Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.9529083, 'lng': -75.1705983},
    'viewport': {'northeast': {'lat': 39.9544300302915,
      'lng': -75.16898036970848},
     'southwest': {'lat': 39.95173206970851, 'lng': -75.1716783302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Sonesta Philadelphia Rittenhouse Square',
   'photos': [{'height': 3024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113046390760426044542">Michael Spampinato</a>'],
     'photo_reference': 'AcYSjRgyi5Zfqwr-SW0GudmEG05VLAhOyrHw5zxu5eKvXMkhgmWL34wAqNvcdjCcU0RQZ8wzLQ5VSSB8OSXO6H_LhNhRUWS0Bdljr5_x0KU59G5YZiXkhrPRR4lQs7NhMfaTZhJ3sekSDPHvZdCuZIQUjmAFnTbXILcbponmZdpf71v6acxN',
     'width': 4032}],
   'place_id': 'ChIJS-B6GTHGxokRtXWy8SVZiM4',
   'plus_code': {'compound_code': 'XR3H+5Q Philadelphia, PA, USA',
    'global_code': '87F6XR3H+5Q'},
   'rating': 4.2,
   'reference': 'ChIJS-B6GTHGxokRtXWy8SVZiM4',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 2471,
   'vicinity': '1800 Market Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.9479028, 'lng': -75.16403269999999},
    'viewport': {'northeast': {'lat': 39.94901273029149,
      'lng': -75.16297066970849},
     'southwest': {'lat': 39.94631476970849, 'lng': -75.1656686302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'DoubleTree by Hilton Hotel Philadelphia Center City',
   'photos': [{'height': 3137,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114457811229226481725">DoubleTree by Hilton Hotel Philadelphia Center City</a>'],
     'photo_reference': 'AcYSjRiUIt74uxKXnaCycdShAWV8mcqkGTw4sNiXuPHCy9P2cB-1l_hF7N1anVWCQCjy1DWe7NE7RRqpiD38OmBesCF0HHxv-JySF8DQYJ5SmCEWULjEqNshvdyT_KKZMiHMut299pEKtJmWvpvV-ixN2o1Rmadz6fj92TBxCR0PF0CUR9cY',
     'width': 4851}],
   'place_id': 'ChIJQ433EiXGxokRnWqMZZoUCDo',
   'plus_code': {'compound_code': 'WRXP+59 Philadelphia, PA, USA',
    'global_code': '87F6WRXP+59'},
   'rating': 4.2,
   'reference': 'ChIJQ433EiXGxokRnWqMZZoUCDo',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 3764,
   'vicinity': '237 South Broad Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.9562836, 'lng': -75.1607484},
    'viewport': {'northeast': {'lat': 39.9575507302915,
      'lng': -75.15931381970849},
     'southwest': {'lat': 39.9548527697085, 'lng': -75.16201178029151}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',

In [10]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():

    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [11]:
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
22,Mogadishu,SO,79.79,broken clouds,2.0371,45.3438,Hotel Juba
23,Toamasina,MG,77.23,broken clouds,-18.1667,49.3833,Hotel H1
30,Kavieng,PG,85.08,broken clouds,-2.5744,150.7967,Nusa Island Retreat
31,Vaini,TO,77.16,light rain,-21.2000,-175.2000,Keleti Beach Resort
32,Faanui,PF,77.11,light rain,-16.4833,-151.7500,Bora-Bora Pearl Beach Resort & Spa
...,...,...,...,...,...,...,...
679,Sinnamary,GF,77.58,overcast clouds,5.3833,-52.9500,ALETHEIA Appartement Sinnamary
684,Fajardo,PR,81.00,broken clouds,18.3258,-65.6524,El Conquistador Resort
686,Pāli,IN,85.42,clear sky,25.7667,73.3333,HOTEL THE AMBA VILAS
694,Oistins,BB,78.89,scattered clouds,13.0667,-59.5333,Butterfly Beach Hotel
698,Butwāl,NP,78.33,clear sky,27.7006,83.4484,Hotel Sindoor Pvt. Ltd.

In [12]:
# Replace empty cell with NaN
hotel_df['Hotel Name'].replace('', np.nan, inplace=True)

In [13]:
hotel_df.count()

City                   177
Country                177
Max Temp               177
Current Description    177
Lat                    177
Lng                    177
Hotel Name             169
dtype: int64

In [14]:
# 7. Drop the rows where there is no Hotel Name.
hotel_clean_df = hotel_df.dropna()

In [15]:
hotel_clean_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
22,Mogadishu,SO,79.79,broken clouds,2.0371,45.3438,Hotel Juba
23,Toamasina,MG,77.23,broken clouds,-18.1667,49.3833,Hotel H1
30,Kavieng,PG,85.08,broken clouds,-2.5744,150.7967,Nusa Island Retreat
31,Vaini,TO,77.16,light rain,-21.2000,-175.2000,Keleti Beach Resort
32,Faanui,PF,77.11,light rain,-16.4833,-151.7500,Bora-Bora Pearl Beach Resort & Spa
34,Mareeba,AU,87.44,scattered clouds,-17.0000,145.4333,Trinity Plains Tourist Park
35,Atuona,PF,77.09,clear sky,-9.8000,-139.0333,Villa Enata
37,Kapaa,US,78.78,clear sky,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
38,Luganville,VU,83.19,few clouds,-15.5333,167.1667,The Espiritu Hotel
40,Auki,SB,82.42,broken clouds,-8.7676,160.7034,Auki Motel

In [16]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
hotel_clean_df.to_csv(output_data_file, index_label="City_ID")

In [17]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template =  """

Hotel Name
{Hotel Name}

City
{City}
Country
{Country}
Current Weather
{Current Description} and {Max Temp} °F


"""
# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_clean_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_clean_df[["Lat", "Lng"]]

In [18]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [ ]:
gmaps.__version__